// @ts-nocheck
'use client'

import React, { useState } from 'react'
import { getSetConfig } from '@/src/utils/setConfigs'
import { STATS_SET_ORDER, STATS_SET_COLORS, DEFAULT_STATS_SET_TAB } from '@/src/utils/statsSetTabs'
import duplicateStats from '@/src/data/duplicateStats.json'
import './duplicate-rates.css'

const CATS = ['Leader', 'Base', 'Common', 'Uncommon', 'Rare', 'Legendary', 'Special']
const fmt2 = (n: number) => (n ?? 0).toFixed(2)

function Distribution({ hist, color }: { hist: number[]; color: string }) {
  const total = hist.reduce((a, b) => a + b, 0) || 1
  const pct = hist.map((h) => (h / total) * 100)
  const max = Math.max(...pct, 1)
  // show 0..8 duplicates
  const bars = pct.slice(0, 9)
  return (
    <div className="dup-dist">
      {bars.map((p, k) => (
        <div className="dup-dist-col" key={k}>
          <div className="dup-dist-bar-track">
            <div
              className="dup-dist-bar"
              style={{ height: `${(p / max) * 100}%`, background: color }}
              title={`${p.toFixed(1)}% of pools have ${k} duplicate${k === 1 ? '' : 's'}`}
            />
          </div>
          <span className="dup-dist-pct">{p >= 1 ? Math.round(p) + '%' : ''}</span>
          <span className="dup-dist-k">{k}</span>
        </div>
      ))}
    </div>
  )
}

const VERDICTS: Record<string, { t: string; c: string }> = {
  consistent: { t: '✓ matches simulation', c: '#16A34A' },
  'minor-drift': { t: '≈ minor drift', c: '#CA8A04' },
  investigate: { t: '⚠ investigate', c: '#DC2626' },
  sparse: { t: 'sparse data', c: '#9aa' },
  'no-data': { t: 'no data yet', c: '#9aa' },
}
function VerdictBadge({ v }: { v: string }) {
  const m = VERDICTS[v] || VERDICTS['no-data']
  return <span className="dup-badge" style={{ color: m.c, borderColor: m.c }}>{m.t}</span>
}
function verdictText(ac: any): string {
  if (!ac || ac.verdict === 'no-data' || ac.n < 1) return 'No opened pools recorded for this set yet — the Actual column fills in as players open sealed pools.'
  if (ac.verdict === 'sparse') return `Only ${ac.n} opened pool${ac.n === 1 ? '' : 's'} so far — need ≥30 for a reliable comparison.`
  const pct = ac.relDiff != null ? (Math.abs(ac.relDiff) * 100).toFixed(1) : '?'
  const dir = ac.relDiff > 0 ? 'above' : 'below'
  if (ac.verdict === 'consistent') return `Actual opened pools (n=${ac.n}) match the simulation within ${pct}% — duplicate generation is behaving as expected.`
  if (ac.verdict === 'minor-drift') return `Actual (n=${ac.n}) sits ${pct}% ${dir} the simulation — within normal variance, or mild drift from older pools generated by an earlier belt version.`
  return `Actual (n=${ac.n}) is ${pct}% ${dir} the simulation (z=${ac.z}). Larger than normal variance — worth checking whether these pools predate the current generator or point to a generation bug.`
}

// At-a-glance health glyph for the headline cards, driven by how well the live
// generator's simulated number matches actual opened pools for this set.
const STATUS: Record<string, { g: string; c: string; t: string }> = {
  consistent: { g: '✓', c: '#16A34A', t: 'matches actual opened pools' },
  'minor-drift': { g: '⚠', c: '#CA8A04', t: 'minor drift from actual opened pools' },
  investigate: { g: '⚑', c: '#DC2626', t: 'differs from actual opened pools — investigate' },
  sparse: { g: '–', c: '#9aa', t: 'too few opened pools to validate yet' },
  'no-data': { g: '–', c: '#9aa', t: 'no opened pools recorded yet' },
}
function StatusIcon({ v, title }: { v: string; title?: string }) {
  const m = STATUS[v] || STATUS['no-data']
  return (
    <span className="dup-status" style={{ color: m.c, borderColor: m.c }} title={title || m.t} aria-label={m.t}>
      {m.g}
    </span>
  )
}

function SetDupView({ code }: { code: string }) {
  const s = (duplicateStats as any).sets?.[code]
  const color = STATS_SET_COLORS[code] || '#888'
  const name = getSetConfig(code)?.setName || code
  if (!s) return <div className="dup-empty">No data for {code}.</div>

  const a = s.sealed6, d = s.draft3
  const ac = s.actual?.nonShuffled || {}
  const sh = s.sealedShuffled
  const acsh = s.actual?.shuffled || {}
  return (
    <div className="dup-view">
      <div className="dup-set-title" style={{ color }}>
        {name} <span className="dup-set-code">({code})</span>
      </div>

      {/* Headline numbers */}
      <div className="dup-headline">
        <div className="dup-stat-card">
          <StatusIcon v={ac.verdict || 'no-data'} title={verdictText(ac)} />
          <div className="dup-stat-label">Sealed — 6-pack pool</div>
          <div className="dup-stat-value" style={{ color }}>{fmt2(a.mean)}</div>
          <div className="dup-stat-sub">duplicate cards / pool</div>
          <div className="dup-ci">95% CI [{fmt2(a.ci95[0])}, {fmt2(a.ci95[1])}]</div>
        </div>
        <div className="dup-stat-card">
          <StatusIcon
            v={ac.verdict || 'no-data'}
            title={`Simulated. The generator is ${(STATUS[ac.verdict] || STATUS['no-data']).t} (validated via sealed pools).`}
          />
          <div className="dup-stat-label">Draft — 3-pack pool</div>
          <div className="dup-stat-value" style={{ color }}>{fmt2(d.mean)}</div>
          <div className="dup-stat-sub">duplicate cards / pool</div>
          <div className="dup-ci">95% CI [{fmt2(d.ci95[0])}, {fmt2(d.ci95[1])}]</div>
        </div>
      </div>

      {/* Three estimates: simulated vs theoretical vs actual */}
      <div className="dup-section">
        <h3>Three estimates (6-pack sealed pool)</h3>
        <div className="dup-compare">
          <div className="dup-compare-row">
            <span className="dup-compare-label">Simulated <span className="dup-tag">live generator</span></span>
            <span className="dup-compare-val" style={{ color }}>{fmt2(a.mean)}</span>
          </div>
          <div className="dup-compare-row">
            <span className="dup-compare-label">Theoretical <span className="dup-tag">variant-collision model</span></span>
            <span className="dup-compare-val">{fmt2(a.theoryMean)}</span>
          </div>
          <div className="dup-compare-row">
            <span className="dup-compare-label">
              Actual <span className="dup-tag">opened pools{ac.n ? ` · n=${ac.n.toLocaleString()}` : ''}</span> <VerdictBadge v={ac.verdict || 'no-data'} />
            </span>
            <span className="dup-compare-val">{ac.n >= 1 && ac.mean != null ? fmt2(ac.mean) : '—'}</span>
          </div>
          <div className="dup-compare-row dup-compare-muted">
            <span className="dup-compare-label">Naive random trials <span className="dup-tag">without collation logic</span></span>
            <span className="dup-compare-val">{fmt2(a.naiveMean)}</span>
          </div>
        </div>
        <p className="dup-note">{verdictText(ac)}</p>
        <p className="dup-note">
          The belt collation makes same-printing repeats ~0, so the naive model over-predicts by 3–4×.
          The variant-collision model (each foil/hyperspace card may collide with a card of the same name
          already in the pool) matches the live generator within ~5–13%.
        </p>
      </div>

      {/* Effect of shuffling */}
      {sh ? (
        <div className="dup-section">
          <h3>Effect of shuffling packs</h3>
          <div className="dup-compare">
            <div className="dup-compare-row">
              <span className="dup-compare-label">Not shuffled <span className="dup-tag">6 consecutive packs</span></span>
              <span className="dup-compare-val">{fmt2(a.mean)} <span className="dup-sigma">σ {fmt2(a.sd)}</span></span>
            </div>
            <div className="dup-compare-row">
              <span className="dup-compare-label">Shuffled <span className="dup-tag">6 packs spread across the box</span></span>
              <span className="dup-compare-val" style={{ color }}>{fmt2(sh.mean)} <span className="dup-sigma">σ {fmt2(sh.sd)}</span></span>
            </div>
          </div>
          <p className="dup-note">
            Shuffling draws your 6 packs from across the 24-pack box, outside each belt's 24-card dedup
            window — so duplicates and their spread both rise. {acsh.n >= 1 ? `Actual shuffled pools: n=${acsh.n}.` : 'No shuffled pools opened yet, so the Actual column above is the not-shuffled case.'}
          </p>
        </div>
      ) : null}

      {/* Distribution */}
      <div className="dup-section">
        <h3>How many duplicates per sealed pool <span className="dup-tag">σ {fmt2(a.sd)}</span></h3>
        <Distribution hist={a.hist} color={color} />
        <p className="dup-note">
          Spread scales with the average: duplicates are a sum of near-independent collision events
          (Poisson-Binomial), so variance ≈ mean. Sets with more variant cards per pack (LAW/ASH,
          with a guaranteed hyperspace common) have both a higher average <em>and</em> a wider spread.
        </p>
      </div>

      {/* Category breakdown */}
      <div className="dup-section">
        <h3>Where the duplicates land (6-pack pool)</h3>
        <table className="dup-table">
          <thead>
            <tr><th>Card type</th><th>Duplicates / pool</th><th>Pool size</th></tr>
          </thead>
          <tbody>
            {CATS.filter((c) => (a.byCat[c] || 0) > 0.001 || (s.poolSizes[c] || 0) > 0).map((c) => (
              <tr key={c}>
                <td>{c}</td>
                <td>{fmt2(a.byCat[c] || 0)}</td>
                <td className="dup-muted">{s.poolSizes[c] || 0}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Variant pairing */}
      <div className="dup-section">
        <h3>What variant pairing causes each duplicate</h3>
        <table className="dup-table">
          <thead><tr><th>Pairing</th><th>Per pool</th></tr></thead>
          <tbody>
            {Object.entries(a.pair).filter(([, v]: any) => v > 0.01).map(([k, v]: any) => (
              <tr key={k}><td>{k}</td><td>{fmt2(v)}</td></tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default function DuplicateRatesPage() {
  const [tab, setTab] = useState(DEFAULT_STATS_SET_TAB)
  const meta = duplicateStats as any
  const tabs = STATS_SET_ORDER.filter((c) => meta.sets?.[c])

  return (
    <div className="app">
      <div className="dup-page">
        <div className="dup-header">
          <h1>Duplicate Rates by Set</h1>
          <p>
            Expected number of duplicate cards per pool — counting a foil, hyperspace, or
            prestige printing as the <em>same card</em> as its normal version.
          </p>
          <p className="dup-subnote">
            Measured from {meta.sampleSizePerSet?.toLocaleString?.() || meta.sampleSizePerSet} simulated
            pools per set using the live pack generator (belts, foils, hyperspace, UC3 &amp; prestige upgrades).
          </p>
        </div>

        <div className="dup-tabs">
          {tabs.map((code) => (
            <button
              key={code}
              className={`dup-tab ${tab === code ? 'active' : ''}`}
              onClick={() => setTab(code)}
              style={
                STATS_SET_COLORS[code]
                  ? ({ '--set-color': STATS_SET_COLORS[code], ...(tab === code ? { backgroundColor: STATS_SET_COLORS[code], borderColor: STATS_SET_COLORS[code] } : {}) } as any)
                  : {}
              }
            >
              {code}
            </button>
          ))}
        </div>

        <div className="dup-content">
          <SetDupView code={tab} />
        </div>

        {meta.generatedAt ? (
          <p className="dup-footer-note">Data generated {meta.generatedAt}. {meta.metric}.</p>
        ) : null}
      </div>
    </div>
  )
}
