import {test,expect,type Page} from '@playwright/test'
async function session(page:Page){
 await page.route('**/api/auth/session',route=>route.fulfill({json:{success:true,data:{user:{id:'00000000-0000-4000-8000-000000000001',username:'Theme tester',is_admin:true,is_alpha_tester:true,is_beta_tester:true}}}}))
 await page.route('**/api/**/patron-status',route=>route.fulfill({json:{success:true,data:{isPatron:true}}}))
 await page.route('**/api/entitlements',route=>route.fulfill({json:{beta:true,canCustomize:true}}))
 await page.route('**/api/lobby',route=>route.fulfill({json:{enabled:true,user:{name:'Theme tester'},activity:{activeGames:0,queuedPlayers:0},capabilities:{queue:true,private:true,ai:true},games:[],history:[],active:null,queue:null}}))
}
for(const width of [1440,390])test(`shared theme follows page navigation at ${width}`,async({page,context},testInfo)=>{
 await page.setViewportSize({width,height:width===390?844:1000})
 await session(page)
 await context.addCookies([{name:'purrgil-table-v1',value:encodeURIComponent(JSON.stringify({theme:'hoth',animations:false})),url:'http://localhost:3000'}])
 for(const path of ['/draft/new?competitive=0','/draft','/sealed','/formats','/history','/stats','/me','/privacy-policy','/terms-of-service','/lobby/constructed','/']){
  await page.goto(path, {waitUntil:'domcontentloaded'})
  await expect(page.locator('body')).toHaveAttribute('data-site-theme','hoth')
  await expect(page.getByRole('button',{name:'Themes',exact:true})).toBeEnabled({timeout:15000})
  await expect(page.getByRole('button',{name:'Settings',exact:true})).toHaveCount(1)
  await expect(page.getByRole('button',{name:'User menu',exact:true})).toHaveCount(1)
  expect(await page.evaluate(()=>getComputedStyle(document.body,'::before').backgroundImage)).toContain('hoth.webp')
  const wallpaper=await page.evaluate(()=>Array.from(document.querySelectorAll('body *')).filter(e=>getComputedStyle(e).backgroundImage.includes('bg-texture-crop')).map(e=>e.className))
  expect(wallpaper,`legacy wallpaper on ${path}`).toEqual([])
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow on ${path}`).toBe(true)
 }
 await page.goto('/draft/new?competitive=0')
 await page.getByRole('button',{name:'Settings',exact:true}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await expect(page.getByRole('tab',{name:'Account',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Close',exact:true}).click()
 await page.getByRole('button',{name:'Themes',exact:true}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await page.getByRole('button',{name:'Close themes',exact:true}).click()
 await expect(page.locator('.set-image').first()).toBeVisible({timeout:15000})
 await expect.poll(()=>page.locator('.set-image').first().evaluate((image:HTMLImageElement)=>image.complete&&image.naturalWidth>0),{timeout:15000}).toBe(true)
 await page.screenshot({path:testInfo.outputPath('themed-draft-setup.png'),fullPage:true})
})
test('root theme is present before JavaScript and survives malformed cookies',async({browser,baseURL})=>{
 const context=await browser.newContext({javaScriptEnabled:false})
 await context.addCookies([{name:'purrgil-table-v1',value:encodeURIComponent(JSON.stringify({theme:'imperial'})),url:baseURL!}])
 const page=await context.newPage()
 await page.goto(`${baseURL}/draft`)
 await expect(page.locator('body')).toHaveAttribute('data-site-theme','imperial')
 await context.addCookies([{name:'purrgil-table-v1',value:'%broken',url:baseURL!}])
 await page.reload()
 await expect(page.locator('body')).toHaveAttribute('data-site-theme','purrgil')
 await context.close()
})

test('changing a theme in setup updates colors and persists into another page',async({page})=>{
 await session(page)
 await page.goto('/draft/new?competitive=0')
 await page.getByRole('button',{name:'Themes',exact:true}).click()
 await page.getByRole('button',{name:'Imperial Holotable',exact:true}).click()
 await page.getByRole('button',{name:/^Use this table/}).click()
 await page.getByRole('button',{name:'Close themes',exact:true}).click()
 await expect(page.locator('body')).toHaveAttribute('data-site-theme','imperial')
 const accent=await page.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--theme-accent'))
 await page.getByRole('link',{name:'Protect the Pod home',exact:true}).click()
 await expect(page.locator('.ph-tile-title')).toHaveText(['Draft','Sealed','Constructed'])
 await expect(page.locator('body')).toHaveAttribute('data-site-theme','imperial')
 expect(await page.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--theme-accent'))).toBe(accent)
 await page.goto('/sealed')
 await expect(page.locator('body')).toHaveAttribute('data-site-theme','imperial')
 expect(await page.evaluate(()=>getComputedStyle(document.body,'::before').backgroundImage)).toContain('imperial.webp')
})
