'use client'
// Canonical shared workspace. scripts/sync-shared-play.mjs copies this, deck-library.ts and its
// stylesheet to Purrgil; the only host-specific input is the authenticated API.
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react'
import './shared-play.css'
import {limitedLibraryFormat, limitedLibraryType, filterLimitedLibrary, fitsQueue} from './deck-library'

type Contract={format:'premier'|'eternal'|'limited';limited:'draft'|'six'|'eight'|'chaos';pool:'current'|'next';set:string;policy?:string}
type Deck={poolShareId:string;name:string;leaderName?:string;baseName?:string;leaderImageUrl?:string;setCode:string;poolType:string;packCount:number|null;ready:boolean;blocker?:string;mainDeckCount?:number}
type State={currentPolicy?:string;signedIn:boolean;enabled:boolean;ptpOrigin:string;playOrigin:string;sets:{code:string;name:string}[];pools:{id:string;name:string}[];queues:{key:string;contract:Contract;label:string;waiting:number}[];pods:{id:string;name:string;set:string;players:number;capacity:number}[];active:null|{id:string;status:string;format:string;contract:Contract;mode:string;invite?:string;error?:string};queue:null|{contract:Contract;label:string;joinedAt:number}}
export type PlayLayoutContext={reserved:boolean;ready:boolean;sets:{code:string;name:string}[];ptpOrigin:string}
type Export={deck:{leader:{id:string;count:number};base:{id:string;count:number};deck:{id:string;count:number}[];sideboard:{id:string;count:number}[]}}
// Every deck file and image comes from swuapi, so PTP, Purrgil and anything else export identical files.
const defaultExportOrigin='https://api.swuapi.com'
const subtype=(v:Contract['limited'])=>({draft:'Draft',six:'Sealed · 6 packs',eight:'Sealed · 8 packs',chaos:'Chaos'})[v]
const label=(c:Contract)=>c.format==='limited'?(c.limited==='chaos'?'Limited · Chaos':`${c.set} · ${subtype(c.limited)}`):c.format==='eternal'?'Eternal':'Premier'
const same=(a:Contract,b:Contract)=>a.format===b.format&&a.pool===b.pool&&(a.format!=='limited'||a.limited===b.limited&&(a.limited==='chaos'||a.set===b.set))
const fits=(c:Contract,d:Deck)=>fitsQueue(c,d)
function Dialog({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>previous?.focus()},[]);return <dialog className="sp-dialog" ref={ref} aria-label={title} onCancel={onClose} onClick={e=>{if(e.target===ref.current){const r=ref.current!.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose()}}}><header><h2>{title}</h2><button aria-label="Close dialog" onClick={onClose}>×</button></header>{children}</dialog>}
function Choices({title,items,value,onChange,disabled=false}:{title:string;items:[string,string][];value:string;onChange:(value:string)=>void;disabled?:boolean}){return <fieldset className="sp-field" disabled={disabled}><legend>{title}</legend><div className="sp-choices">{items.map(([id,name])=><button key={id} type="button" aria-pressed={id===value} onClick={()=>onChange(id)}>{name}</button>)}</div></fieldset>}
export default function PlayWorkspace({endpoint,loginUrl='/login',initialPool='',renderDeckDetails,renderDeckActions,initialFormat='limited',initialContract,renderLayout,onCreateDeck,autoLaunch='always',exportOrigin=defaultExportOrigin}:{autoLaunch?:'always'|'new';endpoint:string;exportOrigin?:string;renderDeckActions?:(deck:Deck)=>ReactNode;initialContract?:Partial<Contract>;loginUrl?:string;initialPool?:string;renderDeckDetails?:(poolShareId:string)=>ReactNode;initialFormat?:Contract['format'];onCreateDeck?:(type:'draft'|'sealed'|'limited')=>void;renderLayout?:(controls:ReactNode,queues:ReactNode,pods:ReactNode,context:PlayLayoutContext)=>ReactNode}){
 const [state,setState]=useState<State>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[anonymous,setAnonymous]=useState(false),[notice,setNotice]=useState('')
 const wanted=useRef<Contract>({format:initialFormat,limited:'six',set:'',pool:'current',...initialContract})
 const [contract,setContract]=useState<Contract>(wanted.current),[decks,setDecks]=useState<Deck[]>([]),[selected,setSelected]=useState(initialPool),[deckError,setDeckError]=useState('')
 const [modal,setModal]=useState<'decks'|'create'|'import'|null>(null),[candidate,setCandidate]=useState(''),[query,setQuery]=useState(''),[filterSet,setFilterSet]=useState('all'),[filterType,setFilterType]=useState('all'),[filterPacks,setFilterPacks]=useState('all'),[incomplete,setIncomplete]=useState(false),[page,setPage]=useState(0)
 const [importText,setImportText]=useState(''),[imported,setImported]=useState<unknown>(),[importName,setImportName]=useState(''),[validation,setValidation]=useState(''),[creation,setCreation]=useState<'draft'|'sealed'>('sealed'),[packs,setPacks]=useState('six')
 const [menu,setMenu]=useState(false),[invite,setInvite]=useState(''),[inviteReady,setInviteReady]=useState(false)
 const request=useRef({key:'',id:''}),requestBusy=useRef(false),initialized=useRef(false),menuRef=useRef<HTMLDivElement>(null),launchRef=useRef(''),sawReservation=useRef(false),sequence=useRef(0),wasReserved=useRef(false)
 const call=useCallback(async<T,>(input?:Record<string,unknown>,signal?:AbortSignal):Promise<T>=>{const res=await fetch(endpoint,{credentials:'same-origin',cache:'no-store',signal:signal?AbortSignal.any([signal,AbortSignal.timeout(30000)]):AbortSignal.timeout(30000),...(input?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}:{})});const data=await res.json();if(!res.ok)throw Error(typeof data.error==='string'?data.error:data.error?.message??'Play is unavailable. Retry safely.');return data},[endpoint])
 const refresh=useCallback(async(signal?:AbortSignal)=>{const n=++sequence.current;try{const next=await call<State>(undefined,signal);if(n!==sequence.current)return;setState(next);setError('');setContract(c=>c.set?c:{...c,set:next.sets[0]?.code??''})}catch(e){if(!signal?.aborted&&n===sequence.current)setError(e instanceof Error?e.message:'Unable to load play.')}},[call])
 useEffect(()=>{const c=new AbortController();void refresh(c.signal);const timer=setInterval(()=>void refresh(c.signal),5000);return()=>{c.abort();clearInterval(timer)}},[refresh])
 const loadDecks=useCallback(async()=>{setDeckError('');try{const result=await call<{decks:Deck[]}>({action:'decks',poolShareId:initialPool});if(!Array.isArray(result.decks))throw Error('Unable to load decks. Retry.');setDecks(result.decks);if(!initialized.current){initialized.current=true;const d=result.decks.find(d=>d.poolShareId===initialPool);if(d){setSelected(d.poolShareId);setContract(c=>({...c,set:d.setCode,limited:d.poolType==='draft'?'draft':d.packCount===8?'eight':'six'}))}else if(initialContract){const first=result.decks.find(d=>fits(wanted.current,d));if(first)setSelected(first.poolShareId)}}}catch(e){setDeckError(e instanceof Error?e.message:'Unable to load decks.')}},[call,initialPool])
 useEffect(()=>{if(state?.signedIn)void loadDecks()},[state?.signedIn,loadDecks])
 useEffect(()=>{const token=new URLSearchParams(location.search).get('invite');if(token)setInvite(token)},[])
 useEffect(()=>{if(!invite||!state?.signedIn)return;let stale=false;void call<{contract:Contract}>({action:'invite',invite}).then(value=>{if(!stale){setContract(value.contract);setInviteReady(true)}}).catch(e=>{if(!stale)setError(e.message)});return()=>{stale=true}},[invite,state?.signedIn,call])
 useEffect(()=>{if(!menu)return;const close=(e:MouseEvent)=>{if(!menuRef.current?.contains(e.target as Node))setMenu(false)};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);document.getElementById('sp-offsite')?.focus()}};document.addEventListener('mousedown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('mousedown',close);document.removeEventListener('keydown',escape)}},[menu])
 const launch=useCallback(async(id:string)=>{try{const result=await call<{launchUrl:string}>({action:'launch',matchId:id});location.assign(result.launchUrl)}catch(e){setError(e instanceof Error?e.message:'Could not open the game.');launchRef.current=''}},[call])
 useEffect(()=>{if(state?.queue||['waiting','starting'].includes(state?.active?.status??''))sawReservation.current=true;const m=state?.active;if(m?.status==='in_progress'&&(autoLaunch==='always'||sawReservation.current)&&launchRef.current!==m.id){launchRef.current=m.id;void launch(m.id)}},[state?.queue,state?.active?.id,state?.active?.status,launch,autoLaunch])
 const deck=decks.find(d=>d.poolShareId===selected),compatible=deck&&fits(contract,deck),reserved=!!state?.active||!!state?.queue
 useEffect(()=>{if(wasReserved.current&&!reserved)request.current={key:'',id:''};wasReserved.current=reserved},[reserved])
 const change=(patch:Partial<Contract>)=>{setContract(c=>({...c,...patch}));setValidation('');setError('')}
 const createLabel=contract.limited==='draft'?'Draft a new deck':contract.limited==='chaos'?'Create a limited deck':'Create new sealed deck'
 const openCreate=()=>{if(onCreateDeck){setModal(null);onCreateDeck(contract.limited==='chaos'?'limited':contract.limited==='draft'?'draft':'sealed');return}setCreation(contract.limited==='draft'?'draft':'sealed');setPacks(contract.limited==='eight'?'eight':'six');setModal('create')}
 const openDecks=()=>{setCandidate(selected);setQuery('');setFilterSet(state?.sets[0]?.code??'all');setFilterType('all');setFilterPacks('all');setPage(0);setModal('decks')}
 const ptp=state?.ptpOrigin??'https://www.protectthepod.com'
 async function act(mode:'queue'|'private'|'ai'){
  if(requestBusy.current)return;requestBusy.current=true;setBusy(true);setError('')
  const input={contract,mode,anonymous,deck:imported,poolShareId:selected,...(invite&&mode==='private'?{invite}:{})},key=JSON.stringify(input)
  if(request.current.key!==key)request.current={key,id:crypto.randomUUID()}
  try{sawReservation.current=true;await call({action:'play',...input,requestId:request.current.id});setInvite('');setInviteReady(false);history.replaceState(null,'',location.pathname);await refresh()}
  catch(e){setError(e instanceof Error?e.message:'Could not enter play.')}
  finally{requestBusy.current=false;setBusy(false)}
 }
 async function cancel(){setBusy(true);try{await call({action:'cancel'});request.current={key:'',id:''};await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function importDeck(){setBusy(true);try{const parsed=JSON.parse(importText);await call({action:'validate',contract,deck:parsed});setImported(parsed);setImportName(parsed.metadata?.name??'Imported deck');setValidation(`Valid for ${label(contract)} · Current`);setModal(null)}catch(e){setValidation(e instanceof Error?e.message:'Invalid deck JSON.')}finally{setBusy(false)}}
 async function exportDeck(destination:'copy'|'save',format:'JSON'|'CSV'|'Melee'|'PNG'){
  setMenu(false);setBusy(true);setError('');try{const data=await call<Export>({action:'export',contract,deck:imported,poolShareId:selected});const name=deck?.name??importName??'Deck'
   const file=name.replace(/[^a-zA-Z0-9 _-]/g,'').trim()||'deck',png=format==='PNG'
   const res=await fetch(png?`${exportOrigin}/deck-image`:`${exportOrigin}/deck-export?format=${format.toLowerCase()}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...data.deck,metadata:{name},...(png?{title:name,layout:contract.format==='limited'?'limited':'default'}:{})}),signal:AbortSignal.timeout(30000)})
   if(!res.ok)throw Error('Deck export is unavailable right now. Try again.')
   const blob=await res.blob()
   if(destination==='copy'&&!png)await navigator.clipboard.writeText(await blob.text())
   else{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${file}.${png?'png':format==='JSON'?'json':format==='CSV'?'csv':'txt'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
   setNotice(`${format} ${destination==='copy'&&!png?'copied':'saved'}.`)
  }catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 const rows:Contract[]=contract.format==='limited'?(['draft','six','eight','chaos'] as const).map(limited=>({...contract,limited})):['premier','eternal'].map(format=>({...contract,format:format as Contract['format']}))
 const visible=filterLimitedLibrary(decks,{format:filterSet,type:filterType,packs:filterPacks,incomplete,query})
 const pages=Math.max(1,Math.ceil(visible.length/6)),current=Math.min(page,pages-1)
 const unavailable=busy||!state?.signedIn||!state?.enabled||reserved||!!error||(contract.format==='limited'?!compatible:!imported)||(!!invite&&!inviteReady)
 const pods=<section className="sp-pods"><div className="sp-section-heading"><h2>Draft pods forming</h2><button onClick={()=>{if(onCreateDeck){onCreateDeck('draft');return}setCreation('draft');setModal('create')}}>Create a pod</button></div><p>Start a new deck together. No deck needed.</p>{state?.pods.length?state.pods.map(p=><div className="sp-pod" key={p.id}><div><strong>{p.name}</strong><small>{p.set} · {p.players}/{p.capacity} players</small><div className="sp-seats" aria-hidden="true">{Array.from({length:Math.min(p.capacity,8)},(_,i)=><i key={i} data-filled={i<p.players}/>)}</div></div><a href={`${ptp}/draft/${encodeURIComponent(p.id)}`}>Join draft</a></div>):<p className="sp-empty">{state?'No pods forming right now.':<span className="skeleton-card" aria-busy="true"/>}</p>}</section>
 const controls=(<section aria-label="Prepare to play">
 {reserved?<div className="sp-waiting"><h2>{state?.queue?'Finding your opponent':state?.active?.status==='waiting'?'Invite someone to play':'Preparing your game'}</h2><p>{state?.queue?.label??state?.active?.format} · Current</p>{state?.queue&&state.currentPolicy&&state.queue.contract.policy!==state.currentPolicy&&<p>The card pool has changed. Cancel this search and re-enter to validate your deck against the current rules.</p>}{state?.active?.error&&<p role="alert">{state.active.error}</p>}{state?.active?.invite&&<><label>Private game link<input readOnly value={`${state.playOrigin}/lobby?invite=${state.active.invite}`} onFocus={e=>e.target.select()}/></label><button onClick={()=>void navigator.clipboard.writeText(`${state.playOrigin}/lobby?invite=${state.active!.invite}`).then(()=>setNotice('Invitation copied.')).catch(()=>setNotice('Select and copy the link above.'))}>Copy link</button></>}{state?.active?.status==='in_progress'?<button onClick={()=>void launch(state.active!.id)}>Open game</button>:<button disabled={busy||state?.active?.status==='starting'} onClick={()=>void cancel()}>Cancel {state?.queue?'search':'invitation'}</button>}</div>:<>
 <Choices title="Format" items={[["premier","Premier"],["eternal","Eternal"],["limited","Limited"]]} value={contract.format} disabled={busy||!!invite} onChange={format=>change({format:format as Contract['format']})}/>
 <Choices title="Card Pool" items={(state?.pools??[{id:'current',name:'Current'}]).map(p=>[p.id,p.name])} value={contract.pool} disabled={busy||!!invite} onChange={pool=>change({pool:pool as Contract['pool']})}/>
 {contract.format==='limited'&&<><Choices title="Limited format" items={[["draft","Draft"],["six","Sealed · 6"],["eight","Sealed · 8"],["chaos","Chaos"]]} value={contract.limited} disabled={busy||!!invite} onChange={limited=>change({limited:limited as Contract['limited']})}/>{contract.limited!=='chaos'?<Choices title="Set" items={(state?.sets??[]).map(s=>[s.code,s.code])} value={contract.set} disabled={busy||!!invite} onChange={set=>change({set})}/>:<p className="sp-help">Any legal limited deck can meet any other: draft, sealed, different sets or pack counts.</p>}</>}
 {invite&&<p className="sp-help">This invitation fixes the format and card pool. Choose a compatible deck to join.</p>}
 <label className="sp-caption">{contract.format==='limited'?'Your limited deck':'Your deck'}</label>
 <button className="sp-deck-trigger" disabled={busy||!state?.signedIn} onClick={()=>contract.format==='limited'?openDecks():setModal('import')} aria-haspopup="dialog">{contract.format==='limited'&&deck?.leaderImageUrl&&<img src={deck.leaderImageUrl} alt=""/>}<span><strong>{contract.format==='limited'?deck?.name??'Choose a saved deck':importName||'Import a deck'}</strong><small>{contract.format==='limited'?(deck?`${limitedLibraryFormat(deck)} · ${limitedLibraryType(deck)} · ${deck.packCount??'?'} packs`:'Browse your PTP limited decks'):'Deck JSON'}</small></span><span>Change ›</span></button>
 {contract.format==='limited'&&<button className="sp-create" onClick={openCreate}>+ {createLabel}</button>}
 {contract.format==='limited'&&deck&&!compatible&&<p className="sp-help">{deck.blocker||'Choose a deck matching this queue, or select Chaos.'}</p>}{contract.format!=='limited'&&validation&&<p className="sp-help">{validation}</p>}
 <div className="sp-contract"><strong>{label(contract)} · {contract.pool==='current'?'Current':'Next Set'}</strong><small>One game · {contract.limited==='chaos'&&contract.format==='limited'?'Any legal limited deck':'Matching format only'}</small></div>
 {!state?.signedIn&&<p className="sp-help"><a href={loginUrl}>Log in with Discord to choose your deck and play</a></p>}
 <label className="sp-anonymous"><input type="checkbox" checked={anonymous} disabled={busy} onChange={e=>setAnonymous(e.target.checked)}/> Hide my name</label><div className="sp-actions"><div className="sp-action-pair"><button className="sp-primary" disabled={unavailable||!!invite} onClick={()=>void act('queue')}>Join {label(contract)} queue</button><button disabled={unavailable} onClick={()=>void act('private')}>{invite?'Join private room':'Create a private room'}</button></div><button disabled={unavailable||!!invite} onClick={()=>void act('ai')}>Play vs AI <span>(Experimental)</span></button>{contract.format==='limited'&&deck&&compatible&&renderDeckActions?.(deck)}
 <div className="sp-offsite" ref={menuRef}><button id="sp-offsite" aria-haspopup="menu" aria-expanded={menu} disabled={busy||(contract.format==='limited'?!deck:!imported)} onClick={()=>setMenu(!menu)} onContextMenu={e=>{e.preventDefault();setMenu(true)}}>Export deck <span aria-hidden="true">⌄</span></button>{menu&&<div className="sp-menu" role="menu" aria-label="Export deck">{(['copy','save'] as const).map(action=><section key={action}><h3>{action==='copy'?'Copy deck':'Save deck'}</h3><div>{(['JSON','CSV','Melee'] as const).map(f=><button role="menuitem" key={f} onClick={()=>void exportDeck(action,f)}>{f}</button>)}</div></section>)}<button role="menuitem" onClick={()=>void exportDeck('save','PNG')}>Save deck image (.png)</button></div>}</div></div>
 </>}
 </section>);
 const queues=(<section><div className="sp-section-heading"><h2>Public queues</h2><small>PTP + Purrgil</small></div><p>{contract.pool==='current'?'Current':'Next Set'} · One game</p>{rows.map(c=>{const count=state?.queues.filter(q=>same(c,q.contract)&&(!state.currentPolicy||q.contract.policy===state.currentPolicy)).reduce((n,q)=>n+q.waiting,0);const eligible=state?.signedIn&&c.format==='limited'?decks.filter(d=>fits(c,d)).length:null;return <div className="sp-queue" key={c.format+c.limited}><strong>{label(c)}</strong><small>{error||!state?'—':count} waiting{eligible!==null&&<> · {eligible} eligible {eligible===1?'deck':'decks'}</>}</small><button disabled={reserved||busy||!!invite} aria-pressed={same(c,contract)} onClick={()=>change(c)}>{same(c,contract)?'Selected':'Select'}</button></div>})}</section>);
 return <section className={`sp-workspace${renderLayout?' sp-embedded':''}`} aria-label="Play">{!renderLayout&&<header className="sp-title"><h1>Play</h1><p>Choose your format and bring a deck.</p></header>}{error&&<div className="sp-error" role="alert">{error}<button onClick={()=>void refresh()}>Retry</button></div>}{notice&&<p role="status">{notice}</p>}
 {renderLayout?renderLayout(controls,queues,pods,{reserved:reserved&&state?.active?.status!=='in_progress',ready:!!state,sets:state?.sets??[],ptpOrigin:ptp}):<div className="sp-layout">{controls}<aside>{queues}{pods}</aside></div>}
 {contract.format==='limited'&&deck?.poolType==='draft'&&renderDeckDetails?.(deck.poolShareId)}
 {modal==='decks'&&<Dialog title="Your limited decks" onClose={()=>setModal(null)}><div className="sp-dialog-body"><p>{label(contract)} · Current</p>{deckError&&<p role="alert">{deckError}<button onClick={()=>void loadDecks()}>Retry</button></p>}<input type="search" aria-label="Search decks" placeholder="Search decks, leaders, or bases" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/><Choices title="Deck type" items={[["all","All"],["draft","Draft"],["sealed","Sealed"]]} value={filterType} onChange={v=>{setFilterType(v);setFilterPacks('all');setPage(0)}}/>{filterType==='sealed'&&<Choices title="Sealed packs" items={[["all","All packs"],["6","6 packs"],["8","8 packs"]]} value={filterPacks} onChange={v=>{setFilterPacks(v);setPage(0)}}/>}<Choices title="Format" items={[["all","All formats"],...[...new Set([...(state?.sets.slice(0,1).map(s=>s.code)??[]),...decks.map(limitedLibraryFormat)])].map(s=>[s,s] as [string,string])]} value={filterSet} onChange={v=>{setFilterSet(v);setPage(0)}}/><div className="sp-filter-options"><label><input type="checkbox" checked={incomplete} onChange={e=>{setIncomplete(e.target.checked);setPage(0)}}/> Show incomplete</label></div><p>{visible.length} {visible.length===1?'deck':'decks'} · {visible.filter(d=>fits(contract,d)).length} compatible</p><div className="sp-deck-grid">{visible.slice(current*6,current*6+6).map(d=><button key={d.poolShareId} className="sp-deck-tile" aria-pressed={candidate===d.poolShareId} disabled={!fits(contract,d)} onClick={()=>setCandidate(d.poolShareId)}>{d.leaderImageUrl&&<img src={d.leaderImageUrl} alt=""/>}<span><strong>{d.name}</strong><small>{d.leaderName}</small><small>{limitedLibraryFormat(d)} · {limitedLibraryType(d)} · {d.packCount??'?'} packs</small><small>{fits(contract,d)?'Ready':d.blocker||'Different limited format'}</small></span></button>)}</div>{!visible.length&&<p className="sp-empty">No matching decks. Change your filters or create a new deck.</p>}{pages>1&&<div className="sp-pagination"><button disabled={current===0} onClick={()=>setPage(current-1)}>Previous</button><span>{current+1} / {pages}</span><button disabled={current===pages-1} onClick={()=>setPage(current+1)}>Next</button></div>}</div><footer><button onClick={openCreate}>+ {createLabel}</button><button className="sp-primary" disabled={!decks.some(d=>d.poolShareId===candidate&&fits(contract,d))} onClick={()=>{setSelected(candidate);setModal(null)}}>Use this deck</button></footer></Dialog>}
 {modal==='create'&&<Dialog title={contract.limited==='chaos'?'Create a limited deck':creation==='draft'?'Draft a new deck':'Create new sealed deck'} onClose={()=>setModal(null)}><div className="sp-dialog-body"><p>Create on Protect the Pod, then choose how to play.</p>{contract.limited==='chaos'&&<Choices title="Build a deck" items={[["draft","Draft"],["sealed","Sealed"]]} value={creation} onChange={v=>setCreation(v as 'draft'|'sealed')}/>}<Choices title="Set" items={(state?.sets??[]).map(s=>[s.code,s.code])} value={contract.set} onChange={set=>change({set})}/>{creation==='sealed'&&<Choices title="Packs" items={[["six","6 packs"],["eight","8 packs"]]} value={packs} onChange={setPacks}/>}<div className="sp-creation-actions">{creation==='draft'?<><a href={`${ptp}/draft/solo`}>Start a solo draft</a><a href={`${ptp}/draft`}>Create a draft pod</a></>:<a href={`${ptp}/pools/new?set=${encodeURIComponent(contract.set)}&packs=${packs==='eight'?8:6}`}>Create sealed pool</a>}</div>{creation==='draft'&&pods}</div></Dialog>}
 {modal==='import'&&<Dialog title="Import a deck" onClose={()=>setModal(null)}><div className="sp-dialog-body"><p className="sp-import-context">{label(contract)} · Current card pool</p><label htmlFor="sp-json">Deck JSON</label><p id="sp-json-help">Paste a deck JSON export below.</p><textarea id="sp-json" aria-describedby="sp-json-help" rows={6} value={importText} maxLength={32000} onChange={e=>setImportText(e.target.value)} placeholder="Paste your deck JSON"/>{validation&&<p role="status">{validation}</p>}</div><footer><button onClick={()=>setModal(null)}>Cancel</button><button className="sp-primary" disabled={busy||!importText.trim()} onClick={()=>void importDeck()}>{busy?'Validating…':'Validate and use deck'}</button></footer></Dialog>}
 </section>
}
