/**
 * Set-level card-presence helpers backed by the tiny generated summary
 * (src/data/cardSummary.json) instead of the ~8 MB cards.json.
 *
 * Client-reachable modules (membership gates, catalog filters, spoiler
 * counters) MUST use these instead of src/utils/cardData's equivalents —
 * importing cardData from client code drags the whole card database into the
 * bundle (CI's bundle guard enforces this). The summary is regenerated by
 * scripts/postProcessCards.ts from the same corrected data, so the two views
 * cannot drift.
 */

import cardSummaryRaw from '../data/cardSummary.json' with { type: 'json' }

export interface SetSummary {
  total: number
  real: number
  normalTotal: number
  normalReal: number
}

const cardSummary = cardSummaryRaw as Record<string, SetSummary>

function summaryFor(setCode: string): SetSummary | null {
  // Carbonite variants (`-CB` suffix) share their base set's cards — same
  // normalization as cardData.hasCardsForSet.
  const baseCode = String(setCode).replace(/-CB$/, '').toUpperCase()
  return cardSummary[baseCode] ?? null
}

/** Mirror of cardData.hasCardsForSet (any card exists for the set). */
export function hasCardsForSet(setCode: string): boolean {
  return (summaryFor(setCode)?.total ?? 0) > 0
}

/** Mirror of cardData.hasRealCardsForSet (≥1 non-placeholder card). */
export function hasRealCardsForSet(setCode: string): boolean {
  return (summaryFor(setCode)?.real ?? 0) > 0
}

/**
 * Normal-variant spoiler progress for a set. Users intuit "X of Y cards
 * spoiled" at the gameplay level (Normal-only), not the doubled-by-treatment
 * inventory count.
 */
export function getNormalSpoilerProgress(setCode: string): { spoiled: number; total: number } {
  const entry = summaryFor(setCode)
  return { spoiled: entry?.normalReal ?? 0, total: entry?.normalTotal ?? 0 }
}
