// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api">> = Specific
  const handler = {} as typeof import("../../../app/api/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/beta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beta">> = Specific
  const handler = {} as typeof import("../../../app/beta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/casual/chaos-draft/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/casual/chaos-draft">> = Specific
  const handler = {} as typeof import("../../../app/casual/chaos-draft/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/casual/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/casual">> = Specific
  const handler = {} as typeof import("../../../app/casual/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/deckbuilder/build/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deckbuilder/build">> = Specific
  const handler = {} as typeof import("../../../app/deckbuilder/build/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/deckbuilder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deckbuilder">> = Specific
  const handler = {} as typeof import("../../../app/deckbuilder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/[shareId]/deck/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft/[shareId]/deck">> = Specific
  const handler = {} as typeof import("../../../app/draft/[shareId]/deck/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/[shareId]/log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft/[shareId]/log">> = Specific
  const handler = {} as typeof import("../../../app/draft/[shareId]/log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/[shareId]/observe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft/[shareId]/observe">> = Specific
  const handler = {} as typeof import("../../../app/draft/[shareId]/observe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/[shareId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/draft/[shareId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/[shareId]/pod/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft/[shareId]/pod">> = Specific
  const handler = {} as typeof import("../../../app/draft/[shareId]/pod/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/[shareId]/report/[poolShareId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft/[shareId]/report/[poolShareId]">> = Specific
  const handler = {} as typeof import("../../../app/draft/[shareId]/report/[poolShareId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/[shareId]/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft/[shareId]/report">> = Specific
  const handler = {} as typeof import("../../../app/draft/[shareId]/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/chaos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft/chaos">> = Specific
  const handler = {} as typeof import("../../../app/draft/chaos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft/new">> = Specific
  const handler = {} as typeof import("../../../app/draft/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft">> = Specific
  const handler = {} as typeof import("../../../app/draft/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft/reports">> = Specific
  const handler = {} as typeof import("../../../app/draft/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft/solo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft/solo">> = Specific
  const handler = {} as typeof import("../../../app/draft/solo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/draft_pool/[shareId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft_pool/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/draft_pool/[shareId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/formats/chaos-draft/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formats/chaos-draft">> = Specific
  const handler = {} as typeof import("../../../app/formats/chaos-draft/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/formats/chaos-sealed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formats/chaos-sealed">> = Specific
  const handler = {} as typeof import("../../../app/formats/chaos-sealed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/formats/pack-blitz/[shareId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formats/pack-blitz/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/formats/pack-blitz/[shareId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/formats/pack-blitz/[shareId]/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formats/pack-blitz/[shareId]/play">> = Specific
  const handler = {} as typeof import("../../../app/formats/pack-blitz/[shareId]/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/formats/pack-blitz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formats/pack-blitz">> = Specific
  const handler = {} as typeof import("../../../app/formats/pack-blitz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/formats/pack-wars/[shareId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formats/pack-wars/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/formats/pack-wars/[shareId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/formats/pack-wars/[shareId]/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formats/pack-wars/[shareId]/play">> = Specific
  const handler = {} as typeof import("../../../app/formats/pack-wars/[shareId]/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/formats/pack-wars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formats/pack-wars">> = Specific
  const handler = {} as typeof import("../../../app/formats/pack-wars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/formats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formats">> = Specific
  const handler = {} as typeof import("../../../app/formats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/formats/rotisserie/[shareId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formats/rotisserie/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/formats/rotisserie/[shareId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/formats/rotisserie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formats/rotisserie">> = Specific
  const handler = {} as typeof import("../../../app/formats/rotisserie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/gift/gc2026/black/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gift/gc2026/black">> = Specific
  const handler = {} as typeof import("../../../app/gift/gc2026/black/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/gift/gc2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gift/gc2026">> = Specific
  const handler = {} as typeof import("../../../app/gift/gc2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../../app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/import">> = Specific
  const handler = {} as typeof import("../../../app/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/me/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/me">> = Specific
  const handler = {} as typeof import("../../../app/me/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/multiplayer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/multiplayer">> = Specific
  const handler = {} as typeof import("../../../app/multiplayer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pool/[shareId]/deck/[buildId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pool/[shareId]/deck/[buildId]">> = Specific
  const handler = {} as typeof import("../../../app/pool/[shareId]/deck/[buildId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pool/[shareId]/deck/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pool/[shareId]/deck">> = Specific
  const handler = {} as typeof import("../../../app/pool/[shareId]/deck/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pool/[shareId]/deck/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pool/[shareId]/deck/play">> = Specific
  const handler = {} as typeof import("../../../app/pool/[shareId]/deck/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pool/[shareId]/deck/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pool/[shareId]/deck/stats">> = Specific
  const handler = {} as typeof import("../../../app/pool/[shareId]/deck/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pool/[shareId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pool/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/pool/[shareId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pools/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pools/new">> = Specific
  const handler = {} as typeof import("../../../app/pools/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../../app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/qa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/qa">> = Specific
  const handler = {} as typeof import("../../../app/qa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sealed/[shareId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sealed/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/sealed/[shareId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sealed/[shareId]/pod/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sealed/[shareId]/pod">> = Specific
  const handler = {} as typeof import("../../../app/sealed/[shareId]/pod/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sealed/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sealed/new">> = Specific
  const handler = {} as typeof import("../../../app/sealed/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sealed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sealed">> = Specific
  const handler = {} as typeof import("../../../app/sealed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sealed/pod/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sealed/pod">> = Specific
  const handler = {} as typeof import("../../../app/sealed/pod/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sealed_pool/[shareId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sealed_pool/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/sealed_pool/[shareId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sets/[setCode]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sets/[setCode]">> = Specific
  const handler = {} as typeof import("../../../app/sets/[setCode]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sets">> = Specific
  const handler = {} as typeof import("../../../app/sets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/showcases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/showcases">> = Specific
  const handler = {} as typeof import("../../../app/showcases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/solo/chaos-draft/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solo/chaos-draft">> = Specific
  const handler = {} as typeof import("../../../app/solo/chaos-draft/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/solo/draft/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solo/draft">> = Specific
  const handler = {} as typeof import("../../../app/solo/draft/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/solo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solo">> = Specific
  const handler = {} as typeof import("../../../app/solo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stats">> = Specific
  const handler = {} as typeof import("../../../app/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/support-the-pod/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support-the-pod">> = Specific
  const handler = {} as typeof import("../../../app/support-the-pod/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms-of-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-service">> = Specific
  const handler = {} as typeof import("../../../app/terms-of-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/grant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/grant">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/grant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/sync-patrons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sync-patrons">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/sync-patrons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/search">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/callback/discord/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/callback/discord">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/callback/discord/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/discord-member/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/discord-member">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/discord-member/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/patron-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/patron-status">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/patron-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/refresh">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/signin/discord/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signin/discord">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/signin/discord/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signout">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/token">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/beta/enroll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beta/enroll">> = Specific
  const handler = {} as typeof import("../../../app/api/beta/enroll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards">> = Specific
  const handler = {} as typeof import("../../../app/api/cards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/lobby/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/lobby/history">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/lobby/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/relay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/relay">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/relay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/thread-update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/thread-update">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/thread-update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/assign-bye/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/assign-bye">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/assign-bye/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/boot/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/boot/[userId]">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/boot/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/build-bot-decks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/build-bot-decks">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/build-bot-decks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/cancel-event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/cancel-event">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/cancel-event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/dev/add-bots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/dev/add-bots">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/dev/add-bots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/drop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/drop">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/drop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/join">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/leave/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/leave">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/leave/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/log">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/log/visibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/log/visibility">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/log/visibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/match/[matchId]/game/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/match/[matchId]/game/claim">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/match/[matchId]/game/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/match/[matchId]/override/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/match/[matchId]/override">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/match/[matchId]/override/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/match/[matchId]/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/match/[matchId]/report">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/match/[matchId]/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/matchmaking/drop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/matchmaking/drop">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/matchmaking/drop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/pause/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/pause">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/pause/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/pick/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/pick">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/pick/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/pod/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/pod">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/pod/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/pool/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/pool">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/pool/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/randomize-packs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/randomize-packs">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/randomize-packs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/randomize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/randomize">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/randomize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/remove/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/remove">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/remove/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/report/[poolShareId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/report/[poolShareId]">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/report/[poolShareId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/report/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/report/notes">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/report/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/report">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/report/slideshow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/report/slideshow">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/report/slideshow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/report/visibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/report/visibility">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/report/visibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/select/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/select">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/select/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/start-matches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/start-matches">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/start-matches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/start">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/state">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/trigger-bots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/trigger-bots">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/trigger-bots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/[shareId]/unlock-decks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/[shareId]/unlock-decks">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/[shareId]/unlock-decks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/history">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft/reports">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/draft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/draft">> = Specific
  const handler = {} as typeof import("../../../app/api/draft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/export/personal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/personal">> = Specific
  const handler = {} as typeof import("../../../app/api/export/personal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/formats/chaos-sealed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/formats/chaos-sealed">> = Specific
  const handler = {} as typeof import("../../../app/api/formats/chaos-sealed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/formats/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/formats/history">> = Specific
  const handler = {} as typeof import("../../../app/api/formats/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/formats/pack-blitz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/formats/pack-blitz">> = Specific
  const handler = {} as typeof import("../../../app/api/formats/pack-blitz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/formats/pack-wars/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/formats/pack-wars">> = Specific
  const handler = {} as typeof import("../../../app/api/formats/pack-wars/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/formats/rotisserie/[shareId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/formats/rotisserie/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/api/formats/rotisserie/[shareId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/formats/rotisserie/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/formats/rotisserie">> = Specific
  const handler = {} as typeof import("../../../app/api/formats/rotisserie/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/image-proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/image-proxy">> = Specific
  const handler = {} as typeof import("../../../app/api/image-proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/create">> = Specific
  const handler = {} as typeof import("../../../app/api/import/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/extract">> = Specific
  const handler = {} as typeof import("../../../app/api/import/extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/re-extract-section/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/re-extract-section">> = Specific
  const handler = {} as typeof import("../../../app/api/import/re-extract-section/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/upload-photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/upload-photo">> = Specific
  const handler = {} as typeof import("../../../app/api/import/upload-photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/decks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/decks">> = Specific
  const handler = {} as typeof import("../../../app/api/me/decks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/drafts/[shareId]/picks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/drafts/[shareId]/picks">> = Specific
  const handler = {} as typeof import("../../../app/api/me/drafts/[shareId]/picks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/drafts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/drafts">> = Specific
  const handler = {} as typeof import("../../../app/api/me/drafts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/play-visit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/play-visit">> = Specific
  const handler = {} as typeof import("../../../app/api/me/play-visit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/pool-history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/pool-history">> = Specific
  const handler = {} as typeof import("../../../app/api/me/pool-history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/pools/[shareId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/pools/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/api/me/pools/[shareId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/pools/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/pools">> = Specific
  const handler = {} as typeof import("../../../app/api/me/pools/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/wayfinder-presence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/wayfinder-presence">> = Specific
  const handler = {} as typeof import("../../../app/api/me/wayfinder-presence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/plugin/v1/match/result/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plugin/v1/match/result">> = Specific
  const handler = {} as typeof import("../../../app/api/plugin/v1/match/result/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/plugin/v1/play/[format]/[shareId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plugin/v1/play/[format]/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/api/plugin/v1/play/[format]/[shareId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/plugin/v1/practice/match-game/lifecycle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plugin/v1/practice/match-game/lifecycle">> = Specific
  const handler = {} as typeof import("../../../app/api/plugin/v1/practice/match-game/lifecycle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/plugin/v1/practice/swiss-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plugin/v1/practice/swiss-summary">> = Specific
  const handler = {} as typeof import("../../../app/api/plugin/v1/practice/swiss-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pods/[shareId]/chat/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pods/[shareId]/chat/history">> = Specific
  const handler = {} as typeof import("../../../app/api/pods/[shareId]/chat/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pods/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pods/public">> = Specific
  const handler = {} as typeof import("../../../app/api/pods/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/[shareId]/build/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools/[shareId]/build">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/[shareId]/build/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/[shareId]/builds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools/[shareId]/builds">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/[shareId]/builds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/[shareId]/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools/[shareId]/claim">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/[shareId]/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/[shareId]/deck.json/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools/[shareId]/deck.json">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/[shareId]/deck.json/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/[shareId]/post-to-discord/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools/[shareId]/post-to-discord">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/[shareId]/post-to-discord/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/[shareId]/randomize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools/[shareId]/randomize">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/[shareId]/randomize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/[shareId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/[shareId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/[shareId]/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools/[shareId]/view">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/[shareId]/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/save-state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools/save-state">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/save-state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/shared/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools/shared">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/shared/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pools/user/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pools/user/[userId]">> = Specific
  const handler = {} as typeof import("../../../app/api/pools/user/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/private/user-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/user-data">> = Specific
  const handler = {} as typeof import("../../../app/api/private/user-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/promo/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promo/claim">> = Specific
  const handler = {} as typeof import("../../../app/api/promo/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/promo/entitlements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promo/entitlements">> = Specific
  const handler = {} as typeof import("../../../app/api/promo/entitlements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/public/draft-log/[shareId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/draft-log/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/api/public/draft-log/[shareId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/public/pack-quality/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/pack-quality">> = Specific
  const handler = {} as typeof import("../../../app/api/public/pack-quality/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sealed/[shareId]/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sealed/[shareId]/join">> = Specific
  const handler = {} as typeof import("../../../app/api/sealed/[shareId]/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sealed/[shareId]/leave/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sealed/[shareId]/leave">> = Specific
  const handler = {} as typeof import("../../../app/api/sealed/[shareId]/leave/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sealed/[shareId]/pod/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sealed/[shareId]/pod">> = Specific
  const handler = {} as typeof import("../../../app/api/sealed/[shareId]/pod/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sealed/[shareId]/pool/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sealed/[shareId]/pool">> = Specific
  const handler = {} as typeof import("../../../app/api/sealed/[shareId]/pool/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sealed/[shareId]/remove/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sealed/[shareId]/remove">> = Specific
  const handler = {} as typeof import("../../../app/api/sealed/[shareId]/remove/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sealed/[shareId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sealed/[shareId]">> = Specific
  const handler = {} as typeof import("../../../app/api/sealed/[shareId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sealed/[shareId]/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sealed/[shareId]/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/sealed/[shareId]/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sealed/[shareId]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sealed/[shareId]/start">> = Specific
  const handler = {} as typeof import("../../../app/api/sealed/[shareId]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sealed/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sealed/history">> = Specific
  const handler = {} as typeof import("../../../app/api/sealed/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sealed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sealed">> = Specific
  const handler = {} as typeof import("../../../app/api/sealed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/archetype-selection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/archetype-selection">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/archetype-selection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/card-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/card-data">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/card-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/deck-inclusion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/deck-inclusion">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/deck-inclusion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/deck/[shareId]/gameplay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/deck/[shareId]/gameplay">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/deck/[shareId]/gameplay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/deck/[shareId]/luck/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/deck/[shareId]/luck">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/deck/[shareId]/luck/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/draft-picks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/draft-picks">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/draft-picks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/generations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/generations">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/generations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/leader-openings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/leader-openings">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/leader-openings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/leader-selection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/leader-selection">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/leader-selection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/leader-winrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/leader-winrate">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/leader-winrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/me/gameplay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/me/gameplay">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/me/gameplay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/me/luck/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/me/luck">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/me/luck/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/me/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/me/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/me/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/pack-actuals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/pack-actuals">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/pack-actuals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/packs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/packs">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/packs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/qa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/qa">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/qa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/tests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/tests">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/tests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stats/top-player-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/top-player-count">> = Specific
  const handler = {} as typeof import("../../../app/api/stats/top-player-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/test/cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/cleanup">> = Specific
  const handler = {} as typeof import("../../../app/api/test/cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/test/create-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/create-user">> = Specific
  const handler = {} as typeof import("../../../app/api/test/create-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/test/live-swiss/cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/live-swiss/cleanup">> = Specific
  const handler = {} as typeof import("../../../app/api/test/live-swiss/cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/test/live-swiss/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/live-swiss/seed">> = Specific
  const handler = {} as typeof import("../../../app/api/test/live-swiss/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/test/live-swiss/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/live-swiss/state">> = Specific
  const handler = {} as typeof import("../../../app/api/test/live-swiss/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/[userId]/showcase-leaders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[userId]/showcase-leaders">> = Specific
  const handler = {} as typeof import("../../../app/api/users/[userId]/showcase-leaders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhooks/patreon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/patreon">> = Specific
  const handler = {} as typeof import("../../../app/api/webhooks/patreon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/formats/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/formats">> = Specific
  const handler = {} as typeof import("../../../app/formats/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pool/[shareId]/deck/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/pool/[shareId]/deck">> = Specific
  const handler = {} as typeof import("../../../app/pool/[shareId]/deck/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
